### ISSUE TITLE
Unnecessary use of cardview

### ISSUE THREAD

**Issue by pieterverstraete** [iRail/BeTrains-for-Android#14]
There are some place where a cardview is used, while it is not really necessary, for example the list of favourites or the compensation text. In these cases there is only 1 card displayed and you have to scroll
within the card. We can remove the cardview to improve the design.

**Comment by ChristopheVersieux** [comment]
I already removed the cards in the traffic issue list, but I personally like the cards in the chat...
But yeah, we can consider removing them...

**Comment by pieterverstraete** [comment]
I don't see any cardviews in the chat?

**Comment by ChristopheVersieux** [comment]
I know there are still design issues, and any help is welcome.
I will continue working on the app and remove all CardViews I may find
