### ISSUE TITLE
Use semantics of traffic issues

### ISSUE THREAD

**Issue by pieterverstraete** [iRail/BeTrains-for-Android#15]
Traffic issues contain a lot of useful information, but are currently received via the RSS feed and displayed in a basic way. If we could get this information is a semantically useful way, we could improve the design of the traffic issue cardviews and provide automatic notifications for the user.

**Comment by pieterverstraete** [comment]
We probably need some support from iRail or NMBS for this.

**Comment by ChristopheVersieux** [comment]
I have added the official traffic info from iRail a long time ago.
