### ISSUE TITLE
Build of 4.510 from source failed with missing @drawable/drawerlogo

### ISSUE THREAD

**Issue by RealRancor** [iRail/BeTrains-for-Android#5]
Hi,

just tried to update the app on F-droid to the latest version 4.510 which is currently failing with this error:

```
/home/vagrant/build/tof.cv.mpp/BeTrains/build/intermediates/res/fdroid/release/layout/list.xml:9: error: Error: No resource found that matches the given name (at 'src' with value '@drawable/drawerlogo').
```

Are there any libs/files missing which could cause this?

**Comment by ChristopheVersieux** [comment]
Missing file hasn't been commited, my bad.
Fixed here: https://github.com/iRail/BeTrains-for-Android/commit/53c4d2205e9fb7aaf4f8462eae58ae36109e75b6

**Comment by RealRancor** [comment]
Hi,

and thanks. That fixed the build on f-droid. :+1:
